import type { Bounty } from "../types";

export const bounties: Bounty[] = [
  {
    id: "b1",
    name: "Fix Login Bug",
    description: "Users are randomly logged out. Investigate session handling and fix the bug.",
    slots: 5,
    isSlotsAvailable: true,
    amount: 1500,
    status: "OPEN",
    type: "BUGFIX",
    expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    link: null,
    locked: false,
    applicationCount: "0",
  },
  {
    id: "b2",
    name: "Optimize API Performance",
    description: "Reduce API response time by improving queries and caching.",
    slots: 3,
    isSlotsAvailable: true,
    amount: 4000,
    status: "OPEN",
    type: "PERFORMANCE",
    expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    link: null,
    locked: false,
    applicationCount: "0",
  },
  {
    id: "b3",
    name: "Build Admin Dashboard",
    description: "Create a role-based admin dashboard with analytics and user management.",
    slots: 2,
    isSlotsAvailable: true,
    amount: 10000,
    status: "OPEN",
    type: "FEATURE",
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    link: null,
    locked: true,
    applicationCount: "0",
  },
];
