name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build frontend
      - name: Build frontend
        run: npm run build

      # 5. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Removing old build..."
            sudo rm -rf /var/www/html/frontend/*
            echo "Copying new build..."
            sudo rsync -avz --chmod=755 /home/ubuntu/landing/dist/ /var/www/html/frontend/
            echo "Setting permissions for Nginx..."
            sudo chown -R www-data:www-data /var/www/html/frontend
            sudo chmod -R 755 /var/www/html/frontend
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            echo "Deployment complete."
